
export const SET_CONVERSATIONS = 'CONVERSATION/SET_CONVERSATIONS'

export const ADD_CONVERSATION = 'CONVERSATION/ADD_CONVERSATION'

export const SET_CURRENT_CONVERSATION = 'CONVERSATION/SET_CURRENT_CONVERSATION'

export const ADD_MESSAGE = 'CONVERSATION/ADD_MESSAGE'

export const SET_DELIVERED = 'CONVERSATION/SET_DELIVERED'
