export const SET_ROOM = 'ROOM/SET_ROOM'

export const SET_ROOM_USERS = 'ROOM/SET_ROOM_USERS'

export const ADD_ROOM_USER = 'ROOM/ADD_ROOM_USER'

export const REMOVE_ROOM_USER = 'ROOM/REMOVE_ROOM_USER'
